// <auto-generated />
using System;
using CandidateManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CandidateManagementSystem.Migrations
{
    [DbContext(typeof(CandidateDBContext))]
    [Migration("20240328111427_AddExperienceToCandidate")]
    partial class AddExperienceToCandidate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CandidateManagementSystem.Models.Candidate", b =>
                {
                    b.Property<int>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CandidateId"));

                    b.Property<DateTime?>("Archived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CandidateId");

                    b.ToTable("Candidates");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            Created = new DateTime(2024, 3, 28, 11, 14, 26, 698, DateTimeKind.Utc).AddTicks(4588),
                            Email = "john.doe@example.com",
                            Experience = 0,
                            Name = "John Doe",
                            Phone = "1234567890"
                        },
                        new
                        {
                            CandidateId = 2,
                            Created = new DateTime(2024, 3, 28, 11, 14, 26, 698, DateTimeKind.Utc).AddTicks(4590),
                            Email = "jane.doe@example.com",
                            Experience = 0,
                            Name = "Jane Doe",
                            Phone = "0987654321"
                        });
                });

            modelBuilder.Entity("CandidateManagementSystem.Models.CandidatePosition", b =>
                {
                    b.Property<int>("CandidateId")
                        .HasColumnType("integer");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.HasKey("CandidateId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("CandidatePositions");

                    b.HasData(
                        new
                        {
                            CandidateId = 1,
                            PositionId = 1
                        },
                        new
                        {
                            CandidateId = 2,
                            PositionId = 2
                        });
                });

            modelBuilder.Entity("CandidateManagementSystem.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime?>("Archived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            Created = new DateTime(2024, 3, 28, 11, 14, 26, 698, DateTimeKind.Utc).AddTicks(4460),
                            Description = "Develops software.",
                            Title = "Software Developer"
                        },
                        new
                        {
                            PositionId = 2,
                            Created = new DateTime(2024, 3, 28, 11, 14, 26, 698, DateTimeKind.Utc).AddTicks(4462),
                            Description = "Works with data.",
                            Title = "Data Scientist"
                        });
                });

            modelBuilder.Entity("CandidateManagementSystem.Models.CandidatePosition", b =>
                {
                    b.HasOne("CandidateManagementSystem.Models.Candidate", "Candidate")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CandidateManagementSystem.Models.Position", "Position")
                        .WithMany("CandidatePositions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CandidateManagementSystem.Models.Candidate", b =>
                {
                    b.Navigation("CandidatePositions");
                });

            modelBuilder.Entity("CandidateManagementSystem.Models.Position", b =>
                {
                    b.Navigation("CandidatePositions");
                });
#pragma warning restore 612, 618
        }
    }
}
